name: DevOps Project 1
on:
  push:
    branches: 
      - main
      - deploy

jobs:
  files-up-to-date:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5
      
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20.19.1'
                
      - name: Install pnpm
        run: npm install
  
      - name: Build
        run: npm run build
        
  
    

      
    
